### ISSUE TITLE
Max Payne 2 can't load d3d8to9

### ISSUE THREAD

**Issue by ThirteenAG** [ThirteenAG/Ultimate-ASI-Loader#26]
Max Payne 2 throws an error with d3d8to9 enabled, however if d3d8.dll is placed separately from ual, it works. Max Payne 1 works fine at the same time.

**Comment by elishacloud** [comment]
I had the same issue with [dxwrapper](https://github.com/elishacloud/dxwrapper).  I believe it is because Max Payne 2 calls either `ValidatePixelShader` or `ValidateVertexShader` (I don't remember which off the top of my head).  The solution is to either remove these exports or to implement them, as I did [here](https://github.com/elishacloud/dxwrapper/blob/20968f1c48b950414997c2dd72385e77f137c70b/d3d8/d3d8.cpp#L42-L91).

**Comment by ThirteenAG** [comment]
Good to know, thanks!

**Comment by ThirteenAG** [comment]
Fixed, but in max payne 2, an ini file is required with this option:
```
[GlobalSets]
FindModule=1
```
I'll add it to widescreen fixes, just in case someone will be enabling d3d8to9, which is useful on laptops.
