### ISSUE TITLE
The release version in the dll file's properties

### ISSUE THREAD

**Issue by eddmanx** [ThirteenAG/Ultimate-ASI-Loader#74]
It seems all releases have file version of 1.2.0.0 and product version of 1.0.0.0.

It's not easy to figure out which exact release is in use, specially when ASI Loader is bundled with other fixes and mods.
Also when doing tests for bugs, etc. it becomes confusing pretty fast with a chance of making mistakes.

Would it be possible to add the release version to the properties?

P.S. Is there a way to download versions older than 4.68? Is there an archive?

**Comment by ThirteenAG** [comment]
Not really, currently appveyor generates a version number and there's no way to get it at compile time.
The only version you should ever need is latest anyway, if there is a regression, it should be reported and fixed.

4.68 is only there because it's the last one that uses dllmain loading, if I remember correctly, current version allows to do that with an ini switch, so there's no reason to use 4.68.

And no, there's no archive.

**Comment by ThirteenAG** [comment]
The idea of having version number at compile time is not bad, and could be implemented it the future.

**Comment by ThirteenAG** [comment]
Added.
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/4904157/8988248b-aee6-40af-a0d1-7105aa2caebe)

**Comment by eddmanx** [comment]
Could it be applied to File version, instead of Product version? That way it'd show up when hovering over it with a mouse.

Zip packages also being versioned would help, although I suppose it's not that important.

**Comment by ThirteenAG** [comment]
Should be good now.
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/4904157/cf3ff099-f3bb-4354-8ba6-653fe1a85998)
